# Generated by Django 4.2.10 on 2024-03-05 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_notes_lastmodified_alter_notes_name_alter_notes_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('FK_Image_Notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.notes')),
            ],
        ),
    ]
